# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a841fbfc1ee0ba0bb977554b3474f0bfa7329874b5b7cef076b9f994228f9f2c1e3746d1e3030fcf3272efa8705511e3b48e3b4f3a1bf35d905a019dd874b47c

test:
  secret_key_base: d3972acaea9dc8c1932022a9f553352e6fb53d749f00b5d53d6de65b68d23eefca76486dce44afe83b39b660c73285fb2c4d9b3e907d8013b1ea5d8e7c8ae278

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
